services:
  - type: web
    name: malicious-url-detector
    runtime: python
    buildCommand: pip install -r requirements.txt && python train.py
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10
